# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Applications Engineer
email: walkerbrianpatrick at gmail.com
description: > 
  This is a personal website for tinkering around with. It might get some
  cool features, it might have weird stuff, and thats ok.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://walkerbrianpatrick.github.io" # the base hostname & protocol for your site
twitter_username: WalkerBrianP
github_username:  walkerbrianpatrick

# Build settings
markdown: kramdown
